---
- name: Gather all registered virtual machines
  hosts: all
  community.vmware.vmware_vm_info:
    hostname: '{{ vcenter_host }}'
    username: '{{ username_secret }}'
    password: '{{ password_secret }}'
  delegate_to: localhost
  register: vminfo