---
- name: Gather all registered virtual machines
  hosts: all
  hostname: '{{ vcenter_host }}'
  username: '{{ username_secret }}'
  password: '{{ password_secret }}'
  delegate_to: localhost
  register: vminfo